version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm run build
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm run test
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - publish:
          requires:
            - build
            - test
          filters:
            only: master
      